version: "3.9"

services:
  go_db:
    container_name: go-db
    image: postgres:12
    environment:
        POSTGRES_PASSWORD: TIOMON@2025
        POSTGRES_USER: TIOMON
        POSTGRES_SB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  pgdata: {}

pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "dev.italloag@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "110716"
    ports:
      - "54321:80"
    depends_on:
      - postgres